{
  description = "Minimal NixOS host using programs.omarchy";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    home-manager = {
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    omarchy-nix = {
      url = "github:zachspar/omarchy-nix";
      inputs.nixpkgs.follows = "nixpkgs";
      inputs.home-manager.follows = "home-manager";
    };
  };

  outputs =
    {
      nixpkgs,
      home-manager,
      omarchy-nix,
      ...
    }:
    {
      nixosConfigurations.omarchy = nixpkgs.lib.nixosSystem {
        system = "x86_64-linux";
        modules = [
          omarchy-nix.nixosModules.default
          home-manager.nixosModules.home-manager
          ./configuration.nix
          {
            home-manager.useGlobalPkgs = true;
            home-manager.useUserPackages = true;
            # Required. NixOS programs.omarchy installs Hyprland + SDDM;
            # this user import writes ~/.config/hypr/hyprland.conf. Skip it
            # and the session is Hyprland's autogenerated stub (SUPER+Q → kitty).
            home-manager.users.alice = {
              imports = [
                omarchy-nix.homeManagerModules.default
                ./home.nix
              ];
            };
          }
        ];
      };
    };
}
