{
  lib,
  config,
  ...
}:
let
  cfg = config.programs.omarchy;
  terminal = lib.getExe cfg.shell.terminalPackage;
  # Wrapper ensures Elephant is up and applies Omarchy's Walker geometry.
  launcher = "omarchy-launch-walker";
  lock = lib.getExe cfg.shell.lockPackage;
  notify = lib.getExe cfg.shell.notificationPackage;
  makoctl = lib.getExe' cfg.shell.notificationPackage "makoctl";
  browser = lib.getExe cfg.apps.browser;
  files = lib.getExe cfg.apps.fileManager;
  editor = lib.getExe cfg.apps.editor;
in
{
  config = lib.mkIf (cfg.enable && cfg.shell.enable) {
    assertions = [
      {
        assertion = config.wayland.windowManager.hyprland.enable;
        message = ''
          programs.omarchy.shell.enable requires Home Manager to manage Hyprland
          (wayland.windowManager.hyprland.enable). Without that, Hyprland writes
          an autogenerated stub at ~/.config/hypr/hyprland.conf (SUPER+Q → kitty)
          instead of Omarchy keybinds (Super+Return Ghostty, Super+Space Walker).

          Do not set wayland.windowManager.hyprland.enable = false while the
          shell pillar is on. Import omarchy-nix.homeManagerModules.default
          and set programs.omarchy.enable = true (inherited from osConfig when
          Home Manager is a NixOS module).
        '';
      }
    ];

    wayland.windowManager.hyprland = {
      enable = true;
      # Home Manager 26.05+ defaults configType to lua (hyprland.lua).
      # Our binds/settings are hyprlang. Pin it or the session file is not
      # ~/.config/hypr/hyprland.conf and Hyprland falls back to autogen.
      configType = "hyprlang";
      # UWSM owns graphical-session.target. HM's hyprland-session.target
      # races it. Without UWSM, HM must start that target or Walker/Waybar
      # (WantedBy = graphical-session.target) never come up.
      systemd.enable = !cfg.shell.withUWSM;
      settings = {
        "$terminal" = terminal;
        "$launcher" = launcher;
        "$browser" = browser;
        "$fileManager" = files;

        exec-once = [
          # Walker + Elephant are systemd user units (see walker.nix).
          # mako has no Home Manager systemd unit; start it with the session
          # the way Omarchy does. hypridle, hyprsunset, and swayosd are
          # started by their user units — do not also exec-once them.
          "${notify}"
        ];

        # Hyprland 0.53+: `noanim, walker` is "invalid field noanim".
        layerrule = [
          "animation none, match:namespace walker"
          "animation none, match:namespace swayosd"
        ];

        general = {
          gaps_in = 5;
          gaps_out = 10;
          border_size = 2;
        };

        decoration = {
          rounding = 8;
        };

        input = {
          follow_mouse = 1;
          kb_options = "compose:caps";
        };

        bind = [
          "SUPER, Return, exec, $terminal"
          "SUPER, Space, exec, $launcher"
          "SUPER CTRL, E, exec, $launcher -m symbols"
          "SUPER CTRL, L, exec, ${lock}"
          "SUPER CTRL, N, exec, omarchy-toggle-nightlight"
          "SUPER, COMMA, exec, ${makoctl} dismiss"
          "SUPER SHIFT, COMMA, exec, ${makoctl} dismiss --all"
        ]
        ++ lib.optionals cfg.theme.enable [
          # Omarchy: Super+Ctrl+Shift+Space opens the theme picker, not cycle.
          # omarchy-theme-next remains the CLI for cycling.
          "SUPER CTRL SHIFT, Space, exec, $launcher -m menus:omarchythemes --width 800 --minheight 400"
          "SUPER CTRL, Space, exec, $launcher -m menus:omarchyBackgroundSelector --width 800 --minheight 400"
        ]
        ++ lib.optionals cfg.apps.enable [
          "SUPER, B, exec, $browser"
          "SUPER SHIFT, F, exec, $fileManager"
          "SUPER, N, exec, $terminal -e ${editor}"
          "SUPER SHIFT, S, exec, omarchy-screenshot"
          "SUPER, V, exec, $launcher -m clipboard"
        ];

        bindm = [
          "SUPER, mouse:272, movewindow"
          "SUPER, mouse:273, resizewindow"
        ];

        # Omarchy media.conf: bindel/bindl so volume and brightness still
        # work on the lock screen. Caps/Num/Scroll Lock OSD is the NixOS
        # libinput backend, not a Hyprland bind (avoids double-firing).
        "$osdclient" = "omarchy-swayosd-client";

        bindel = [
          ", XF86AudioRaiseVolume, exec, $osdclient --output-volume raise"
          ", XF86AudioLowerVolume, exec, $osdclient --output-volume lower"
          ", XF86AudioMute, exec, $osdclient --output-volume mute-toggle"
          ", XF86AudioMicMute, exec, $osdclient --input-volume mute-toggle"
          ", XF86MonBrightnessUp, exec, $osdclient --brightness raise"
          ", XF86MonBrightnessDown, exec, $osdclient --brightness lower"
          "ALT, XF86AudioRaiseVolume, exec, $osdclient --output-volume +1"
          "ALT, XF86AudioLowerVolume, exec, $osdclient --output-volume -1"
          "ALT, XF86MonBrightnessUp, exec, $osdclient --brightness +1"
          "ALT, XF86MonBrightnessDown, exec, $osdclient --brightness -1"
        ];

        bindl = [
          ", XF86AudioNext, exec, $osdclient --playerctl next"
          ", XF86AudioPause, exec, $osdclient --playerctl play-pause"
          ", XF86AudioPlay, exec, $osdclient --playerctl play-pause"
          ", XF86AudioPrev, exec, $osdclient --playerctl previous"
        ];

      };
      extraConfig = lib.optionalString cfg.theme.enable ''
        source = ${config.xdg.stateHome}/omarchy/current/hyprland.conf
      '';
    };

    # Replace a leftover Hyprland autogen stub. Without force, Home Manager
    # leaves ~/.config/hypr/hyprland.conf alone and the session stays on
    # SUPER+Q → kitty.
    xdg.configFile."hypr/hyprland.conf".force = true;

    # Hyprland prefers hyprland.lua when both exist (0.55+). Drop an
    # autogenerated lua stub so the managed hyprlang file is what loads.
    home.activation.omarchyReplaceAutogenHyprland = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
      lua="${config.xdg.configHome}/hypr/hyprland.lua"
      if [ -e "$lua" ] && grep -qE 'autogenerated|AUTOGENERATED' "$lua"; then
        rm -f "$lua"
      fi
    '';

    # UWSM does not read home.sessionVariables. Point it at HM's file so
    # OMARCHY_THEME / NIXOS_OZONE_WL land in the compositor session.
    xdg.configFile."uwsm/env" = lib.mkIf cfg.shell.withUWSM {
      source = "${config.home.sessionVariablesPackage}/etc/profile.d/hm-session-vars.sh";
    };

    # Waybar is Omarchy's status bar. systemd starts it; do not also exec-once.
    # The comment used to claim this; the option was never set, so a session
    # without an exec-once bar stayed empty even when Hyprland was managed.
    programs.waybar = {
      enable = true;
      systemd.enable = true;
    };
  };
}
