{
  lib,
  pkgs,
  config,
  ...
}:
let
  cfg = config.programs.omarchy;
  terminal = lib.getExe cfg.shell.terminalPackage;
  # Wrapper ensures Elephant is up and applies Omarchy's Walker geometry.
  launcher = "omarchy-launch-walker";
  lock = lib.getExe cfg.shell.lockPackage;
  notify = lib.getExe cfg.shell.notificationPackage;
  makoctl = lib.getExe' cfg.shell.notificationPackage "makoctl";
  browser = lib.getExe cfg.apps.browser;
  files = lib.getExe cfg.apps.fileManager;
  editor = lib.getExe cfg.apps.editor;
  # Bare `exec` under hyprland-uwsm is often a silent no-op. Omarchy wraps
  # every user-facing launch with uwsm-app so the app gets a systemd scope.
  # Session helpers that talk to an already-running daemon (hyprlock, makoctl,
  # hyprsunset toggle, swayosd-client) stay unwrapped.
  app = cmd: if cfg.shell.withUWSM then "uwsm-app -- ${cmd}" else cmd;
  # Hyprland bindd: "MODS, KEY, Description, dispatcher, args"
  workspaces = lib.genList (i: i + 1) 10;
  workspaceKey = n: "code:${toString (9 + n)}";
in
{
  config = lib.mkIf (cfg.enable && cfg.shell.enable) {
    assertions = [
      {
        assertion = config.wayland.windowManager.hyprland.enable;
        message = ''
          programs.omarchy.shell.enable requires Home Manager to manage Hyprland
          (wayland.windowManager.hyprland.enable). Without that, Hyprland writes
          an autogenerated stub at ~/.config/hypr/hyprland.conf (SUPER+Q → kitty)
          instead of Omarchy keybinds (Super+Return Ghostty, Super+Space Walker,
          Super+W close, Super+K keybindings).

          Do not set wayland.windowManager.hyprland.enable = false while the
          shell pillar is on. Import omarchy-nix.homeManagerModules.default
          and set programs.omarchy.enable = true (inherited from osConfig when
          Home Manager is a NixOS module).
        '';
      }
    ];

    wayland.windowManager.hyprland = {
      enable = true;
      # Home Manager 26.05+ defaults configType to lua (hyprland.lua).
      # Omarchy master is still hyprlang. Pin it or the session file is not
      # ~/.config/hypr/hyprland.conf and Hyprland falls back to autogen.
      configType = "hyprlang";
      # UWSM owns graphical-session.target. HM's hyprland-session.target
      # races it. Without UWSM, HM must start that target or Walker/Waybar
      # (WantedBy = graphical-session.target) never come up.
      systemd.enable = !cfg.shell.withUWSM;
      settings = {
        "$terminal" = terminal;
        "$launcher" = launcher;
        "$browser" = browser;
        "$fileManager" = files;
        "$osdclient" = "omarchy-swayosd-client";

        exec-once = [
          # Walker + Elephant are systemd user units (see walker.nix).
          # mako has no Home Manager systemd unit; start it with the session
          # the way Omarchy does. Under UWSM that means uwsm-app so the
          # daemon gets a scope. hypridle, hyprsunset, and swayosd are
          # started by their user units — do not also exec-once them.
          (app notify)
        ];

        # default/hypr/envs.conf (subset). NIXOS_OZONE_WL is set on NixOS.
        env = [
          "XCURSOR_SIZE,24"
          "HYPRCURSOR_SIZE,24"
          "GDK_BACKEND,wayland,x11,*"
          "QT_QPA_PLATFORM,wayland;xcb"
          "MOZ_ENABLE_WAYLAND,1"
          "ELECTRON_OZONE_PLATFORM_HINT,wayland"
          "OZONE_PLATFORM,wayland"
        ];

        xwayland = {
          force_zero_scaling = true;
        };

        # default/hypr/looknfeel.conf
        general = {
          gaps_in = 5;
          gaps_out = 10;
          border_size = 2;
          layout = "dwindle";
          resize_on_border = false;
          allow_tearing = false;
        };

        decoration = {
          rounding = 0;
          shadow = {
            enabled = true;
            range = 2;
            render_power = 3;
          };
          blur = {
            enabled = true;
            size = 2;
            passes = 2;
            special = true;
            brightness = 0.60;
            contrast = 0.75;
          };
        };

        dwindle = {
          preserve_split = true;
          force_split = 2;
        };

        master = {
          new_status = "master";
        };

        misc = {
          disable_hyprland_logo = true;
          disable_splash_rendering = true;
          disable_scale_notification = true;
          focus_on_activate = true;
          on_focus_under_fullscreen = 1;
        };

        cursor = {
          hide_on_key_press = true;
          warp_on_change_workspace = 1;
        };

        binds = {
          hide_special_on_workspace_change = true;
        };

        # default/hypr/input.conf
        input = {
          follow_mouse = 1;
          sensitivity = 0;
          kb_options = "compose:caps";
          touchpad = {
            natural_scroll = false;
          };
        };

        # default/hypr/windows.conf — Hyprland 0.53+ match: syntax.
        windowrule = [
          "suppress_event maximize, match:class .*"
          "tag +default-opacity, match:class .*"
          "no_focus on, match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0"
          "opacity 0.985 0.96, match:tag default-opacity"
        ];

        layerrule = [
          "animation none, match:namespace walker"
          "animation none, match:namespace swayosd"
        ];

        # bindd so Super+K (omarchy-menu-keybindings) can show descriptions.
        # App chords are default/hypr/plain-bindings.conf: Shift variants so
        # they do not collide with tiling-v2 (Super+F is fullscreen).
        bindd = [
          "SUPER, Return, Terminal, exec, ${app "$terminal"}"
          "SUPER, Space, Launch apps, exec, ${app "$launcher"}"
          "SUPER CTRL, E, Emoji picker, exec, ${app "$launcher -m symbols"}"
          "SUPER, K, Show key bindings, exec, ${app "omarchy-menu-keybindings"}"
          "SUPER CTRL, L, Lock system, exec, ${lock}"
          "SUPER CTRL, N, Toggle nightlight, exec, omarchy-toggle-nightlight"
          "SUPER, COMMA, Dismiss last notification, exec, ${makoctl} dismiss"
          "SUPER SHIFT, COMMA, Dismiss all notifications, exec, ${makoctl} dismiss --all"

          # default/hypr/bindings/tiling-v2.conf
          "SUPER, W, Close window, killactive"
          "SUPER, J, Toggle window split, layoutmsg, togglesplit"
          "SUPER, P, Pseudo window, pseudo"
          "SUPER, T, Toggle window floating/tiling, togglefloating"
          "SUPER, F, Full screen, fullscreen, 0"
          "SUPER CTRL, F, Tiled full screen, fullscreenstate, 0 2"
          "SUPER ALT, F, Full width, fullscreen, 1"
          "SUPER, LEFT, Focus on left window, movefocus, l"
          "SUPER, RIGHT, Focus on right window, movefocus, r"
          "SUPER, UP, Focus on above window, movefocus, u"
          "SUPER, DOWN, Focus on below window, movefocus, d"
          "SUPER SHIFT, LEFT, Swap window to the left, swapwindow, l"
          "SUPER SHIFT, RIGHT, Swap window to the right, swapwindow, r"
          "SUPER SHIFT, UP, Swap window up, swapwindow, u"
          "SUPER SHIFT, DOWN, Swap window down, swapwindow, d"
          "SUPER, S, Toggle scratchpad, togglespecialworkspace, scratchpad"
          "SUPER ALT, S, Move window to scratchpad, movetoworkspacesilent, special:scratchpad"
          "SUPER, TAB, Next workspace, workspace, e+1"
          "SUPER SHIFT, TAB, Previous workspace, workspace, e-1"
          "SUPER CTRL, TAB, Former workspace, workspace, previous"
          "SUPER SHIFT ALT, LEFT, Move workspace to left monitor, movecurrentworkspacetomonitor, l"
          "SUPER SHIFT ALT, RIGHT, Move workspace to right monitor, movecurrentworkspacetomonitor, r"
          "SUPER SHIFT ALT, UP, Move workspace to up monitor, movecurrentworkspacetomonitor, u"
          "SUPER SHIFT ALT, DOWN, Move workspace to down monitor, movecurrentworkspacetomonitor, d"
          "ALT, TAB, Focus on next window, cyclenext"
          "ALT SHIFT, TAB, Focus on previous window, cyclenext, prev"
          "CTRL ALT, TAB, Focus on next monitor, focusmonitor, +1"
          "CTRL ALT SHIFT, TAB, Focus on previous monitor, focusmonitor, -1"
          "SUPER, code:20, Expand window left, resizeactive, -100 0"
          "SUPER, code:21, Shrink window left, resizeactive, 100 0"
          "SUPER SHIFT, code:20, Shrink window up, resizeactive, 0 -100"
          "SUPER SHIFT, code:21, Expand window down, resizeactive, 0 100"
          "SUPER, mouse_down, Scroll active workspace forward, workspace, e+1"
          "SUPER, mouse_up, Scroll active workspace backward, workspace, e-1"
          "SUPER, G, Toggle window grouping, togglegroup"
          "SUPER ALT, G, Move active window out of group, moveoutofgroup"
          "SUPER ALT, LEFT, Move window to group on left, moveintogroup, l"
          "SUPER ALT, RIGHT, Move window to group on right, moveintogroup, r"
          "SUPER ALT, UP, Move window to group on top, moveintogroup, u"
          "SUPER ALT, DOWN, Move window to group on bottom, moveintogroup, d"
          "SUPER ALT, TAB, Next window in group, changegroupactive, f"
          "SUPER ALT SHIFT, TAB, Previous window in group, changegroupactive, b"
        ]
        ++ lib.concatMap (n: [
          "SUPER, ${workspaceKey n}, Switch to workspace ${toString n}, workspace, ${toString n}"
          "SUPER SHIFT, ${workspaceKey n}, Move window to workspace ${toString n}, movetoworkspace, ${toString n}"
          "SUPER SHIFT ALT, ${workspaceKey n}, Move window silently to workspace ${toString n}, movetoworkspacesilent, ${toString n}"
        ]) workspaces
        ++ lib.optionals cfg.theme.enable [
          "SUPER CTRL SHIFT, Space, Theme menu, exec, ${app "$launcher -m menus:omarchythemes --width 800 --minheight 400"}"
          "SUPER CTRL, Space, Theme background menu, exec, ${app "$launcher -m menus:omarchyBackgroundSelector --width 800 --minheight 400"}"
        ]
        ++ lib.optionals cfg.apps.enable [
          "SUPER SHIFT, Return, Browser, exec, ${app "$browser"}"
          "SUPER SHIFT, B, Browser, exec, ${app "$browser"}"
          "SUPER SHIFT ALT, B, Browser (private), exec, ${app "$browser --incognito"}"
          "SUPER SHIFT, F, File manager, exec, ${app "$fileManager"}"
          "SUPER SHIFT, N, Editor, exec, ${app "$terminal -e ${editor}"}"
          "SUPER SHIFT, S, Screenshot, exec, ${app "omarchy-screenshot"}"
          ", PRINT, Screenshot, exec, ${app "omarchy-screenshot"}"
          # default/hypr/bindings/clipboard.conf
          "SUPER, C, Universal copy, sendshortcut, CTRL, Insert, activewindow"
          "SUPER, V, Universal paste, sendshortcut, SHIFT, Insert, activewindow"
          "SUPER, X, Universal cut, sendshortcut, CTRL, X, activewindow"
          "SUPER CTRL, V, Clipboard manager, exec, ${app "$launcher -m clipboard"}"
        ];

        bindm = [
          "SUPER, mouse:272, movewindow"
          "SUPER, mouse:273, resizewindow"
        ];

        # default/hypr/bindings/media.conf — bindel/bindl so volume and
        # brightness still work on the lock screen. Caps/Num/Scroll Lock OSD
        # is the NixOS libinput backend, not a Hyprland bind.
        bindel = [
          ", XF86AudioRaiseVolume, exec, $osdclient --output-volume raise"
          ", XF86AudioLowerVolume, exec, $osdclient --output-volume lower"
          ", XF86AudioMute, exec, $osdclient --output-volume mute-toggle"
          ", XF86AudioMicMute, exec, $osdclient --input-volume mute-toggle"
          ", XF86MonBrightnessUp, exec, $osdclient --brightness raise"
          ", XF86MonBrightnessDown, exec, $osdclient --brightness lower"
          "ALT, XF86AudioRaiseVolume, exec, $osdclient --output-volume +1"
          "ALT, XF86AudioLowerVolume, exec, $osdclient --output-volume -1"
          "ALT, XF86MonBrightnessUp, exec, $osdclient --brightness +1"
          "ALT, XF86MonBrightnessDown, exec, $osdclient --brightness -1"
        ];

        bindl = [
          ", XF86AudioNext, exec, $osdclient --playerctl next"
          ", XF86AudioPause, exec, $osdclient --playerctl play-pause"
          ", XF86AudioPlay, exec, $osdclient --playerctl play-pause"
          ", XF86AudioPrev, exec, $osdclient --playerctl previous"
        ];
      };
      extraConfig = lib.optionalString cfg.theme.enable ''
        source = ${config.xdg.stateHome}/omarchy/current/hyprland.conf
      '';
    };

    # Replace a leftover Hyprland autogen stub. Without force, Home Manager
    # leaves ~/.config/hypr/hyprland.conf alone and the session stays on
    # SUPER+Q → kitty.
    xdg.configFile."hypr/hyprland.conf".force = true;

    # Hyprland prefers hyprland.lua when both exist (0.55+). Drop an
    # autogenerated lua stub so the managed hyprlang file is what loads.
    home.activation.omarchyReplaceAutogenHyprland = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
      lua="${config.xdg.configHome}/hypr/hyprland.lua"
      if [ -e "$lua" ] && grep -qE 'autogenerated|AUTOGENERATED' "$lua"; then
        rm -f "$lua"
      fi
    '';

    # uwsm-app must be on PATH for Super+Return etc. NixOS already installs
    # pkgs.uwsm; this covers standalone Home Manager.
    home.packages = lib.optionals cfg.shell.withUWSM [ pkgs.uwsm ];

    # UWSM does not read home.sessionVariables. Point it at HM's file so
    # OMARCHY_THEME / NIXOS_OZONE_WL land in the compositor session.
    xdg.configFile."uwsm/env" = lib.mkIf cfg.shell.withUWSM {
      source = "${config.home.sessionVariablesPackage}/etc/profile.d/hm-session-vars.sh";
    };

    # Waybar is Omarchy's status bar. systemd starts it; do not also exec-once.
    programs.waybar = {
      enable = true;
      systemd.enable = true;
    };
  };
}
