{
  # Under NixOS + home-manager.nixosModules.home-manager, programs.omarchy
  # is inherited from osConfig. That is what writes Hyprland / Waybar /
  # Walker. A NixOS-only enable leaves ~/.config/hypr/hyprland.conf as
  # Hyprland's autogenerated stub.
  #
  # Standalone Home Manager (no osConfig):
  #   programs.omarchy.enable = true;

  home.username = "alice";
  home.homeDirectory = "/home/alice";
  home.stateVersion = "25.11";
}
