{
  lib,
  pkgs,
  config,
  options,
  ...
}:
let
  cfg = config.programs.omarchy;
  palettes = import ../shared/palettes.nix;
  fallback = palettes.tokyo-night;
  palette =
    if cfg.theme.enable && builtins.hasAttr cfg.theme.name palettes then
      palettes.${cfg.theme.name}
    else
      fallback;

  greeter = pkgs.callPackage ../../pkgs/omarchy-greeter {
    themeName = if cfg.theme.enable then cfg.theme.name else "tokyo-night";
    background = palette.background;
    foreground = palette.foreground;
    failedColor = palette.red;
    logo = cfg.shell.greeter.logo;
  };

  sessionName = if cfg.shell.withUWSM then "hyprland-uwsm" else "hyprland";
  greeterOn = cfg.enable && cfg.shell.enable && cfg.shell.greeter.enable;
in
{
  config = lib.mkMerge (
    [
      (lib.mkIf (cfg.enable && cfg.shell.enable) {
        assertions = [
          {
            # NixOS programs.hyprland only installs the compositor and the
            # SDDM session. Keybinds, Waybar, Walker, and mako live in Home
            # Manager. Skip this and Hyprland writes the autogenerated stub
            # (SUPER+Q → kitty) the first time you log in.
            assertion =
              (options ? home-manager)
              && lib.any (u: u.wayland.windowManager.hyprland.enable or false) (
                lib.attrValues config.home-manager.users
              );
            message = ''
              programs.omarchy.shell.enable is on, but no Home Manager user has
              wayland.windowManager.hyprland.enable. Hyprland will write an
              autogenerated stub at ~/.config/hypr/hyprland.conf (SUPER+Q → kitty)
              instead of Omarchy keybinds (Super+Return Ghostty, Super+Space Walker).
              Walker, Waybar, and mako stay down for the same reason.

              Minimal NixOS + Home Manager wiring:

                {
                  imports = [
                    omarchy-nix.nixosModules.default
                    home-manager.nixosModules.home-manager
                  ];
                  programs.omarchy.enable = true;
                  home-manager.useGlobalPkgs = true;
                  home-manager.useUserPackages = true;
                  home-manager.users.YOURUSER = {
                    imports = [ omarchy-nix.homeManagerModules.default ];
                    home.stateVersion = "25.11";
                  };
                }

              This module also injects the Home Manager module via
              home-manager.sharedModules when Home Manager is imported, so the
              per-user import is belt-and-suspenders. You still need
              home-manager.users.<name> so activation writes ~/.config/hypr.

              Standalone Home Manager: import homeManagerModules.default and set
              programs.omarchy.enable = true on the user.

              If ~/.config/hypr/hyprland.conf already exists from a first login,
              the next Home Manager switch replaces it (force). Log out and back
              in, or hyprctl reload.
            '';
          }
        ];

        programs.hyprland = {
          enable = true;
          withUWSM = cfg.shell.withUWSM;
          xwayland.enable = true;
        };

        # Walker + Elephant user units live in Home Manager (walker.nix). NixOS
        # only installs the packages so the binaries exist on PATH.

        xdg.portal = {
          enable = true;
          extraPortals = [ pkgs.xdg-desktop-portal-gtk ];
        };

        programs.dconf.enable = true;

        environment.sessionVariables = {
          NIXOS_OZONE_WL = "1";
          OMARCHY_THEME_DIR = "/run/current-system/sw/share/omarchy/themes";
        };

        fonts.packages = [
          pkgs.nerd-fonts.jetbrains-mono
        ];

        # Hyprlock authenticates via PAM. The Home Manager package alone cannot
        # unlock; this empty service is what nixpkgs programs.hyprlock installs.
        # Do not enable programs.hyprlock here — that also starts a system
        # hypridle unit that would race the Home Manager one.
        security.pam.services.hyprlock = { };

        # Caps/Num/Scroll Lock OSD. Must be a system unit (needs /dev/input);
        # Home Manager cannot own it. udev + dbus configs come from the package.
        # Volume/brightness remain Hyprland bindel/bindl → swayosd-client, same
        # as Omarchy's media.conf — the backend is lock-key feedback, not a
        # second volume path.
        services.udev.packages = [ cfg.shell.osdPackage ];
        services.dbus.packages = [ cfg.shell.osdPackage ];
        systemd.services.swayosd-libinput-backend = {
          description = "SwayOSD LibInput backend for Caps/Num/Scroll Lock";
          documentation = [ "https://github.com/ErikReider/SwayOSD" ];
          wantedBy = [ "graphical.target" ];
          after = [ "graphical.target" ];
          serviceConfig = {
            Type = "simple";
            ExecStart = lib.getExe' cfg.shell.osdPackage "swayosd-libinput-backend";
            Restart = "on-failure";
          };
        };

        environment.systemPackages = [
          cfg.shell.terminalPackage
          cfg.shell.launcherPackage
          cfg.shell.barPackage
          cfg.shell.lockPackage
          cfg.shell.idlePackage
          cfg.shell.notificationPackage
          cfg.shell.nightlightPackage
          cfg.shell.osdPackage
          pkgs.elephant
          pkgs.playerctl
          pkgs.jq
          pkgs.libnotify
          pkgs.libqalculate
          pkgs.uwsm
          (pkgs.callPackage ../../pkgs/omarchy-theme-tools { })
        ];
      })

      (lib.mkIf greeterOn {
        assertions = [
          {
            assertion = !cfg.shell.greeter.autoLogin.enable || cfg.shell.greeter.autoLogin.user != null;
            message = ''
              programs.omarchy.shell.greeter.autoLogin.enable is true but
              programs.omarchy.shell.greeter.autoLogin.user is unset.
            '';
          }
        ];

        # Omarchy's first-login path: SDDM (Wayland) + Hyprland/UWSM session.
        # Autologin stays off. FDE unlock is Plymouth / cryptsetup, not this.
        services.displayManager.defaultSession = lib.mkDefault sessionName;

        services.displayManager.autoLogin = lib.mkIf cfg.shell.greeter.autoLogin.enable {
          enable = true;
          user = cfg.shell.greeter.autoLogin.user;
        };

        services.displayManager.sddm = {
          enable = true;
          wayland = {
            enable = true;
          }
          // lib.optionalAttrs (cfg.shell.greeter.compositor == "weston") {
            compositor = "weston";
          };
          theme = "omarchy";
          extraPackages = [ greeter ];
          settings = lib.mkMerge [
            {
              Theme.Current = "omarchy";
            }
            (lib.mkIf (cfg.shell.greeter.compositor == "hyprland") {
              Wayland.CompositorCommand = "${lib.getExe' config.programs.hyprland.package "Hyprland"} --config ${greeter}/share/sddm/hyprland.conf";
            })
          ];
        };

        environment.systemPackages = [ greeter ];

        boot.plymouth = lib.mkIf cfg.shell.greeter.plymouth.enable {
          enable = true;
          theme = "omarchy";
          themePackages = [ greeter ];
        };

        warnings =
          lib.optionals
            (
              cfg.shell.greeter.plymouth.enable
              && cfg.storage.enable
              && (cfg.storage.luks.device != null || cfg.storage.disko.enable)
              && !config.boot.initrd.systemd.enable
            )
            [
              ''
                programs.omarchy.shell.greeter.plymouth is on and a LUKS device is
                declared, but boot.initrd.systemd.enable is false. NixOS's
                traditional initrd may still show the cryptsetup text prompt
                before Plymouth starts. Set boot.initrd.systemd.enable = true
                for the themed unlock dialog (Omarchy's unlock.png path).
              ''
            ];
      })
    ]
    # mkIf still *defines* home-manager even when the condition is false.
    # Only emit the attr when the HM NixOS module is actually imported.
    ++ lib.optionals (options ? home-manager) [
      (lib.mkIf (cfg.enable && cfg.shell.enable) {
        # Every HM user on this host gets the Omarchy user stubs when the
        # NixOS module is composed with home-manager.nixosModules.home-manager.
        # Users should still import homeManagerModules.default; this closes
        # the "I enabled programs.omarchy on NixOS and forgot the user import"
        # hole that produces the autogenerated Hyprland banner.
        home-manager.sharedModules = [ ../home-manager ];
      })
    ]
  );
}
